# MCP HTTP Proxy Configuration for Demo REST API
# This configuration uses the simplified backend structure

backends:
  # Main API Backend
  - base_url: "http://localhost:8181"
    default_headers:
      - type: constant
        name: Authorization
        value: "Bearer token-here"
      - type: constant
        name: Content-Type
        value: "application/json"
      - type: constant
        name: Accept
        value: "application/json"
      - type: constant
        name: User-Agent
        value: "MCP-HTTP-Proxy/1.0"

    endpoints:
      # TOOL: Create a new customer order
      - capability: tool
        mode: webhook
        name: create_order
        path: "/api/orders"
        method: POST
        description: "Creates a new customer order with items and shipping details. Use when a customer wants to place an order or buy products."

        wait_response: true
        response_timeout: 30s

        body_params:
          - data_type: string
            value_type: dynamic
            description: "customer's full name"
            identifier: customer_name
            required: true
          - data_type: string
            value_type: dynamic
            description: "customer's email address"
            identifier: customer_email
            required: true
          - data_type: array
            value_type: dynamic
            description: "array of order items, each with product_id, quantity, and optional customizations"
            identifier: items
            required: true
          - data_type: object
            value_type: dynamic
            description: "shipping address with street, city, state, zip, and country"
            identifier: shipping_address
            required: true
          - data_type: boolean
            value_type: dynamic
            description: "whether customer wants express shipping (faster delivery)"
            identifier: express_shipping
            required: false
          - data_type: string
            value_type: constant
            description: "order source identifier"
            identifier: source
            required: false

      # TOOL: Send UI notification to user
      - capability: tool
        mode: client
        name: show_notification
        path: "/api/notifications"
        method: POST
        description: "Displays a notification message to the user interface. Use for alerts, confirmations, status updates, or important information."

        # Override default content-type for this specific endpoint
        headers:
          - type: constant
            name: X-Notification-Channel
            value: "ui"

        wait_response: false
        response_timeout: 5s

        body_params:
          - data_type: string
            value_type: dynamic
            description: "notification title or headline"
            identifier: title
            required: true
          - data_type: string
            value_type: dynamic
            description: "detailed notification message"
            identifier: message
            required: true
          - data_type: string
            value_type: dynamic
            description: "notification type: info, success, warning, or error"
            identifier: type
            required: false

      # TOOL: Update user preferences and settings
      - capability: tool
        mode: webhook
        name: update_user_preferences
        path: "/api/users/{user_id}/preferences"
        method: PATCH
        description: "Updates user account preferences including notifications, privacy settings, language, and timezone. Use when customer wants to change their settings."

        wait_response: true
        response_timeout: 20s

        path_parameters:
          - data_type: string
            value_type: dynamic
            description: "user's unique identifier (like user123)"
            identifier: user_id
            required: true

        body_params:
          - data_type: object
            value_type: dynamic
            description: "notification preferences with email, sms, and push settings"
            identifier: notifications
            required: false
          - data_type: object
            value_type: dynamic
            description: "privacy settings including data_sharing and marketing preferences"
            identifier: privacy
            required: false
          - data_type: string
            value_type: dynamic
            description: "preferred language code (en, es, fr, de, it)"
            identifier: language
            required: false
          - data_type: string
            value_type: dynamic
            description: "timezone identifier (like America/Los_Angeles)"
            identifier: timezone
            required: false

      # RESOURCE: Get user profile information
      - capability: resource
        name: user_profile
        path: "/api/users/{user_id}/profile"
        method: GET
        description: "Retrieves comprehensive user profile including personal info, address, preferences, and account details. Reference this for personalized responses."

        wait_response: true
        response_timeout: 15s

        path_parameters:
          - data_type: string
            value_type: dynamic
            description: "user's unique identifier (like user123)"
            identifier: user_id
            required: true

      # RESOURCE: Search product catalog
      - capability: resource
        name: product_search
        path: "/api/products/search"
        method: GET
        description: "Searches the product catalog with filters. Use when customer asks about products, pricing, availability, or wants to browse items."

        # Additional headers specific to product search
        headers:
          - type: constant
            name: X-Search-Version
            value: "v2"
          - type: constant
            name: X-Include-Analytics
            value: "true"

        wait_response: true
        response_timeout: 20s

        query_parameters:
          - data_type: string
            value_type: dynamic
            description: "search query or product keywords"
            identifier: search
            required: false
          - data_type: string
            value_type: dynamic
            description: "product category filter (electronics, accessories, etc.)"
            identifier: category
            required: false
          - data_type: number
            value_type: dynamic
            description: "minimum price filter"
            identifier: min_price
            required: false
          - data_type: number
            value_type: dynamic
            description: "maximum price filter"
            identifier: max_price
            required: false
          - data_type: boolean
            value_type: dynamic
            description: "only show products that are in stock"
            identifier: in_stock_only
            required: false
          - data_type: number
            value_type: constant
            description: "maximum number of results to return (default: 20)"
            identifier: limit
            required: false

      # RESOURCE: Check order status
      - capability: resource
        name: order_status
        path: "/api/orders/{order_id}/status"
        method: GET
        description: "Retrieves current order status, delivery estimates, and tracking information. Use when customer asks about their order."

        wait_response: true
        response_timeout: 10s

        path_parameters:
          - data_type: string
            value_type: dynamic
            description: "order number or order ID (like ORD1001)"
            identifier: order_id
            required: true

      # PROMPT: Generate customer service email
      - capability: prompt
        name: customer_service_email
        path: "/api/templates/email"
        method: POST
        description: "Generates professional customer service email templates for order confirmations, shipping updates, refunds, or general inquiries."

        # Template-specific headers
        headers:
          - type: constant
            name: X-Template-Version
            value: "v2.1"
          - type: constant
            name: X-Template-Engine
            value: "advanced"

        wait_response: true
        response_timeout: 15s

        body_params:
          - data_type: string
            value_type: dynamic
            description: "customer's first name"
            identifier: customer_name
            required: true
          - data_type: string
            value_type: dynamic
            description: "email subject line"
            identifier: subject
            required: true
          - data_type: string
            value_type: dynamic
            description: "template type: order_confirmation, shipping_update, refund_processed, or general_inquiry"
            identifier: template_type
            required: true
          - data_type: object
            value_type: dynamic
            description: "specific context data like order details, tracking numbers, or issue information"
            identifier: context_data
            required: false
          - data_type: string
            value_type: constant
            description: "sender name and title for email signature"
            identifier: sender_signature
            required: false
          - data_type: string
            value_type: dynamic
            description: "email tone: formal, friendly, apologetic, or celebratory"
            identifier: tone
            required: false

      # PROMPT: Generate multilingual welcome message
      - capability: prompt
        name: welcome_message
        path: "/api/templates/welcome"
        method: POST
        description: "Generates personalized welcome messages in multiple languages with cultural considerations. Use for new users, returning customers, or account upgrades."

        # Localization-specific headers
        headers:
          - type: constant
            name: X-Localization-Service
            value: "v3.0"
          - type: dynamic
            name: X-User-Language
            value: "user's preferred language from conversation"

        wait_response: true
        response_timeout: 10s

        body_params:
          - data_type: string
            value_type: dynamic
            description: "target language code (en, es, fr, de, it)"
            identifier: language
            required: true
          - data_type: string
            value_type: dynamic
            description: "customer's name for personalization"
            identifier: customer_name
            required: true
          - data_type: string
            value_type: dynamic
            description: "welcome context: new_signup, returning_user, or premium_upgrade"
            identifier: context
            required: true
          - data_type: object
            value_type: dynamic
            description: "additional personalization data like location, interests, or account details"
            identifier: personalization
            required: false
          - data_type: boolean
            value_type: constant
            description: "include cultural greetings and customs in the message"
            identifier: cultural_context
            required: false
